# Generated by Django 5.0.2 on 2024-03-06 15:59

from django.db import migrations

dependencies = [
    ("core", "0008_complianceassessment_folder_riskassessment_folder"),
    ("iam", "0001_initial"),
]


def set_folder(apps, schema_editor):
    ComplianceAssessment = apps.get_model("core", "ComplianceAssessment")
    RiskAssessment = apps.get_model("core", "RiskAssessment")
    RiskScenario = apps.get_model("core", "RiskScenario")
    for comp_assessment in ComplianceAssessment.objects.all():
        comp_assessment.folder = comp_assessment.project.folder
        comp_assessment.save()
    for risk_assessment in RiskAssessment.objects.all():
        risk_assessment.folder = risk_assessment.project.folder
        risk_assessment.save()
    for risk_scenario in RiskScenario.objects.all():
        risk_scenario.folder = risk_scenario.risk_assessment.project.folder
        risk_scenario.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_complianceassessment_folder_riskassessment_folder"),
    ]

    operations = [
        migrations.RunPython(set_folder),
    ]
